---
title: "basic_analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(echo = FALSE)
```

# to do list:
1. change code so that we get graph per player and can filter for type, player #, position
2. get logistic to work
3. make spreadsheet format correct and reproducible/automatic
4. try to make the sliders for the graphs on shiny

## R Markdown

```{r basic_analysis}
# load relevant packages -----------------------------------------------------#
library(tidyverse)
library(readxl)
library(gridExtra)
library(ggspectra)
#-----------------------------------------------------------------------------#

# read data ------------------------------------------------------------------#
volleyball_data <- read_excel("SAMPLE DATA- TWU FRI.xlsx")
#-----------------------------------------------------------------------------#

# combine cut-spin and spin as spin in the serve_type column -----------------#
`%notin%` <- Negate(`%in%`)

data <- 
  volleyball_data %>% 
  mutate(serve_type = replace(volleyball_data$serve_type,
                              volleyball_data$serve_type == "cut_spin",
                              "spin"),
         server = as.numeric(server)) %>% 
  filter(!is.na(server),
         server %notin% c(0, 4, 99, 19))
#-----------------------------------------------------------------------------#

# check counts of each serve_type --------------------------------------------#
count_serve_type <- 
  data %>% 
  group_by(serve_type) %>% 
  summarize(counts = n())
#-----------------------------------------------------------------------------#

# check main serve type for each server --------------------------------------#
main_serve_type <- 
  data %>%
  group_by(server, serve_type) %>% 
  summarise(n = n(),
            error_perc = sum(is.na(serve_outcome))/n) %>% 
  group_by(server) %>% 
  slice_max(order_by = n)
#-----------------------------------------------------------------------------#

# semi-join data with main_serve_type_for_player to get corresponding complete data rows
main_serve_type_data <- 
  data %>% 
  semi_join(main_serve_type,
            by = c("server", "serve_type"))
#-----------------------------------------------------------------------------#

# create new column to assign probabilities for each serve outcome -----------#
point_prob_data <- 
  main_serve_type_data %>%
  mutate(point_probability = case_when(serve_outcome == 0 ~ 1,
                                       serve_outcome == 1 ~ 0.614,
                                       serve_outcome == 2 ~ 0.473,
                                       serve_outcome == 3 ~ 0.329,
                                       serve_outcome == 4 ~ 0.366,
                                       TRUE ~ 0)
  )
#-----------------------------------------------------------------------------#

# calculate average point scoring probability and ----------------------------#
# average error percentage for each serve speed per player -------------------#
avg_point_prob_data <- 
  point_prob_data %>%
  group_by(server, serve_speed) %>% 
  summarize(avg_prob = mean(point_probability),
            avg_err_perc = sum(point_probability == 0)/n(),
            avg_ace_perc = sum(point_probability == 1)/n()) %>% 
  arrange(server)
#-----------------------------------------------------------------------------#

# perform k-smoothing on serve_speed vs avg_prob & error_perc ----------------#
ksmooth_values <- 
  avg_point_prob_data %>%
  group_by(server) %>% 
  summarize(ksmooth_point_prob = list(ksmooth(x = serve_speed,
                                              y = avg_prob,
                                              kernel = "normal",
                                              bandwidth = 5,
                                              n.points = n())), 
            ksmooth_error_perc = list(ksmooth(x = serve_speed,
                                              y = avg_err_perc,
                                              kernel = "normal",
                                              bandwidth = 5,
                                              n.points = n())),
            ksmooth_ace_perc = list(ksmooth(x = serve_speed,
                                            y = avg_ace_perc,
                                            kernel = "normal",
                                            bandwidth = 5,
                                            n.points = n()))
  ) %>% 
  unnest_wider(col = c(ksmooth_point_prob,
                       ksmooth_error_perc,
                       ksmooth_ace_perc),
               names_sep = "") %>% 
  unnest(col = -server) %>% 
  select(-4, -6) %>% 
  setNames(., c("server",
                "serve_velocity",
                "point_prob",
                "error_perc",
                "ace_perc")) 
#-----------------------------------------------------------------------------#

# wrangle ksmooth data to obtain most optimal serve speeds for each server ---#
top2_serve_velocity <- 
  ksmooth_values %>% 
  select(server, serve_velocity, point_prob) %>% 
  group_by(server) %>% 
  slice_max(order_by = point_prob, n = 2)
#-----------------------------------------------------------------------------#

# obtain most optimal serve speed per server ---------------------------------#  
optimal_serve_velocity <- 
  top2_serve_velocity %>% 
  slice(seq(1, nrow(.), 2))
#-----------------------------------------------------------------------------#

# obtain second most optimal serve speed per server --------------------------#
second_serve_velocity <- 
  top2_serve_velocity %>% 
  slice(seq(2, nrow(.), 2))
#-----------------------------------------------------------------------------#

# create top 2 most optimal serve speeds per server table --------------------#
plus_minus_2 <- function(x) {
  ## this function adds and subtracts 2 from the optimum serve speed to
  ## obtain the optimal serve speed range
  return(paste0("[", x-2, ", ", x+2, "]"))
}

optimal_serve_velocity_table <- 
  left_join(optimal_serve_velocity,
            second_serve_velocity,
            by = "server") %>% 
  mutate(optimal_serve_velocity = round(serve_velocity.x, 0),
         second_optimal_serve_velocity = round(serve_velocity.y, 0),
         optimal_point_prob = round(point_prob.x, 3),
         second_optimal_point_prob = round(point_prob.y, 3),
         optimal_velocity_range = sapply(optimal_serve_velocity, plus_minus_2),
         second_optimal_velocity_range = sapply(second_optimal_serve_velocity, plus_minus_2)) %>% 
  select(1, 6, 8, 10, 7, 9, 11)
#-----------------------------------------------------------------------------#
```

```{r plot, fig.width=12, fig.height=50}
# create a plots of ksmooth values for point probability, -------------------#
# error percentage and ace percentage on the y-axis and ---------------------#
# serve speed on the x-axis -------------------------------------------------#

# manipulate ksmooth_values dataframe to get a type column which has 
# one column called Type containing the different types of percentage i.e
# point earning percentage, error percentage and ace percentage
plot_data <- 
  ksmooth_values %>% 
  pivot_longer(cols = c(point_prob, error_perc, ace_perc),
               names_to = "type",
               values_to = "percentage")

# create the ggplot which is faceted into subplots for each server
main_plot <- 
  plot_data %>%
  ggplot(aes(x = serve_velocity, y = percentage)) +
  geom_line(aes(color = type)) +
  facet_wrap(vars(server), ncol = 1, scales = "free") +
  labs(x = "Serve Speed (km/h)", y = "", color = "") +
  scale_color_discrete(labels = c("Ace Percentage",
                                  "Error Percentage",
                                  "Earn Percentage")) +
  theme_bw()

# add and label the local maxima points on the point earning percentage
# line for each server
final_main_plot <- ggplot_build(main_plot)
main_plot + 
  stat_peaks(data = plot_data %>% filter(type == "point_prob"),
             aes(x = serve_velocity, y = percentage),
             span = 5,
             color = "black"
  ) +
  stat_peaks(data = plot_data %>% filter(type == "point_prob"),
             aes(x = serve_velocity,
                 y = percentage,
                 label = paste0(as.numeric(after_stat(y.label))*100,
                               "% at ",
                               after_stat(x.label),
                               " km/h")),
             span = 5,
             geom = "text",
             vjust = -0.5,
             size = 3)

#-----------------------------------------------------------------------------#
```

```{r logistic_regression}
library(MASS)
roster_number = 2
point_data <- volleyball_data %>% drop_na(point_outcome)
point_data$server_to<- as.factor(point_data$server_to)
point_data$serve_tape<- as.factor(point_data$serve_tape)
point_data$serve_outcome<- as.factor(point_data$serve_outcome)


full_logistic <- point_data  %>%
mutate(serve_outcome = coalesce(serve_outcome, "err")) 


all_player_logistic <- glm(point_outcome ~ server_to + serve_type + server_to*passer_position + passer_position + serve_tape+serve_speed+serve_outcome+ seam_positioning, data=  full_logistic, family= binomial)

summary(all_player_logistic)
#full_backwards <- all_player_logistic %>% stepAIC(trace= FALSE)
#coef(full_backwards)


#point_data <- point_data %>% mutate(seams == ifelse(server_to == 1 & passer_position == or("LL","LC","LH")),"1-6",7)


#logistic_player_data <- point_data %>% filter(server == roster_number) %>% select(-point) %>%
# select(-server) %>% select(-serve_from) %>% select(-serve_outcome_overpass) %>%
#  mutate(serve_outcome = coalesce(serve_outcome, "err")) 
logistic_player_data <- full_logistic %>% filter(server== roster_number)
# logistic_player_data <- point_data %>% filter(server == roster_number)
# # 
# # sapply(lapply(logistic_player_data,unique),length)
# # 
# fullmod <- glm(point_outcome ~ server_to + serve_type + serve_tape+serve_speed+serve_outcome+ passer_position, data=  logistic_player_data, family= binomial)
player_full_mod <- glm(point_outcome ~ server_to + serve_type + server_to*passer_position + passer_position + serve_tape+serve_speed+serve_outcome+seam_positioning, data=  logistic_player_data, family= binomial)
# summary(fullmod)
summary(player_full_mod)
# #  
#backwards <- player_full_mod %>%stepAIC(trace= FALSE)
# # 
# coef(backwards)
```
<!-- git push -u origin master -->

